# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - mozillavpn_taskgraph.transforms.release_artifacts:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - signing

jobs:
    msi:
        description: repackage mozillavpn msi
        run-on-tasks-for: [github-push]
        fetches:
            signing:
                - artifact: MozillaVPN.zip
                  dest: ../build/src
        dependencies:
            signing: signing-windows/opt
        if-dependencies: [signing]
        worker-type: b-win2012
        worker:
            max-run-time: 3600
        release-artifacts: [MozillaVPN.msi]
        attributes:
            build-type: windows/opt
        run:
            using: run-task
            cwd: build/src/windows/installer
            command: [cmd.exe, /c, build_prod.cmd]
        treeherder:
            symbol: rpk(msi)
            kind: build
            tier: 1
            platform: windows/x86_64

    rpm:
        description: repackage mozillavpn rpm
        run-on-tasks-for: [github-push, github-release]
        fetches:
            signing:
                - artifact: target.tar.gz
                  dest: fetches
        dependencies:
            signing: signing-linux/opt
        if-dependencies: [signing]
        worker-type: b-linux
        worker:
            max-run-time: 3600
            chain-of-trust: true
            docker-image: {in-tree: fedora}
        release-artifacts: [mozillavpn.rpm]
        attributes:
            build-type: linux/opt
        run:
            using: run-task
            cwd: '{checkout}'
            command: ./taskcluster/scripts/package/rpm.sh
        treeherder:
            symbol: rpk(rpm)
            kind: build
            tier: 1
            platform: linux/opt